version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/jaejkim/data/mariadb:/var/lib/mysql
    expose:
      - 3306:3306
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - /home/jaejkim/data/wordpress:/var/www/html
    expose:
      - 9000:9000
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - /home/jaejkim/data/wordpress:/var/www/html
    ports:
      - 80:80
    restart: always