version: '3'

services:
  maria-db:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/jaejkim/data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - /home/jaejkim/data/nginx:/var/log/nginx
      - /home/jaejkim/data/nginx/conf:/etc/nginx/conf.d
    ports:
      - 80:80

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - /home/jaejkim/data/wordpress:/var/www/html
    ports:
      - 8080:8080