version: '3'

services:
  # maria-db:
  #   build:
  #     context: ./requirements/mariadb
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /home/jaejkim/data/mariadb:/var/lib/mysql
  #   ports:
  #     - 3306:3306

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - /home/jaejkim/data/wordpress:/var/www/html
    expose:
      - 9000

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - /home/jaejkim/data/wordpress:/var/www/html
    ports:
      - 80:80