version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/jaejkim/data/mariadb:/var/lib/mysql
    expose:
      - 3306
    restart: always
    networks:
      - mynetwork
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on: 
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - /home/jaejkim/data/wordpress:/var/www/html
    expose:
      - 9000
    restart: always
    networks:
      - mynetwork
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - mariadb
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - /home/jaejkim/data/wordpress:/var/www/html
    ports:
      - 443:443
    restart: always
    networks:
      - mynetwork
    env_file:
      - .env

networks:
  mynetwork:
    driver: bridge

